/*
 * This file is generated by jOOQ.
*/
package gov.nist.csrk.jooq.tables.daos;


import gov.nist.csrk.jooq.tables.Capabilities;
import gov.nist.csrk.jooq.tables.records.CapabilitiesRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CapabilitiesDao extends DAOImpl<CapabilitiesRecord, gov.nist.csrk.jooq.tables.pojos.Capabilities, Integer> {

    /**
     * Create a new CapabilitiesDao without any configuration
     */
    public CapabilitiesDao() {
        super(Capabilities.CAPABILITIES, gov.nist.csrk.jooq.tables.pojos.Capabilities.class);
    }

    /**
     * Create a new CapabilitiesDao with an attached configuration
     */
    public CapabilitiesDao(Configuration configuration) {
        super(Capabilities.CAPABILITIES, gov.nist.csrk.jooq.tables.pojos.Capabilities.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(gov.nist.csrk.jooq.tables.pojos.Capabilities object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>Id IN (values)</code>
     */
    public List<gov.nist.csrk.jooq.tables.pojos.Capabilities> fetchById(Integer... values) {
        return fetch(Capabilities.CAPABILITIES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>Id = value</code>
     */
    public gov.nist.csrk.jooq.tables.pojos.Capabilities fetchOneById(Integer value) {
        return fetchOne(Capabilities.CAPABILITIES.ID, value);
    }

    /**
     * Fetch records that have <code>Domain IN (values)</code>
     */
    public List<gov.nist.csrk.jooq.tables.pojos.Capabilities> fetchByDomain(String... values) {
        return fetch(Capabilities.CAPABILITIES.DOMAIN, values);
    }

    /**
     * Fetch records that have <code>Container IN (values)</code>
     */
    public List<gov.nist.csrk.jooq.tables.pojos.Capabilities> fetchByContainer(String... values) {
        return fetch(Capabilities.CAPABILITIES.CONTAINER, values);
    }

    /**
     * Fetch records that have <code>Capability IN (values)</code>
     */
    public List<gov.nist.csrk.jooq.tables.pojos.Capabilities> fetchByCapability(String... values) {
        return fetch(Capabilities.CAPABILITIES.CAPABILITY, values);
    }

    /**
     * Fetch records that have <code>Capability2 IN (values)</code>
     */
    public List<gov.nist.csrk.jooq.tables.pojos.Capabilities> fetchByCapability2(String... values) {
        return fetch(Capabilities.CAPABILITIES.CAPABILITY2, values);
    }

    /**
     * Fetch records that have <code>UniqueId IN (values)</code>
     */
    public List<gov.nist.csrk.jooq.tables.pojos.Capabilities> fetchByUniqueid(String... values) {
        return fetch(Capabilities.CAPABILITIES.UNIQUEID, values);
    }

    /**
     * Fetch records that have <code>Description IN (values)</code>
     */
    public List<gov.nist.csrk.jooq.tables.pojos.Capabilities> fetchByDescription(String... values) {
        return fetch(Capabilities.CAPABILITIES.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>CSADescription IN (values)</code>
     */
    public List<gov.nist.csrk.jooq.tables.pojos.Capabilities> fetchByCsadescription(String... values) {
        return fetch(Capabilities.CAPABILITIES.CSADESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>Notes IN (values)</code>
     */
    public List<gov.nist.csrk.jooq.tables.pojos.Capabilities> fetchByNotes(String... values) {
        return fetch(Capabilities.CAPABILITIES.NOTES, values);
    }

    /**
     * Fetch records that have <code>Scopes IN (values)</code>
     */
    public List<gov.nist.csrk.jooq.tables.pojos.Capabilities> fetchByScopes(String... values) {
        return fetch(Capabilities.CAPABILITIES.SCOPES, values);
    }

    /**
     * Fetch records that have <code>C IN (values)</code>
     */
    public List<gov.nist.csrk.jooq.tables.pojos.Capabilities> fetchByC(Integer... values) {
        return fetch(Capabilities.CAPABILITIES.C, values);
    }

    /**
     * Fetch records that have <code>I IN (values)</code>
     */
    public List<gov.nist.csrk.jooq.tables.pojos.Capabilities> fetchByI(Integer... values) {
        return fetch(Capabilities.CAPABILITIES.I, values);
    }

    /**
     * Fetch records that have <code>A IN (values)</code>
     */
    public List<gov.nist.csrk.jooq.tables.pojos.Capabilities> fetchByA(Integer... values) {
        return fetch(Capabilities.CAPABILITIES.A, values);
    }

    /**
     * Fetch records that have <code>ResponsibilityVector IN (values)</code>
     */
    public List<gov.nist.csrk.jooq.tables.pojos.Capabilities> fetchByResponsibilityvector(String... values) {
        return fetch(Capabilities.CAPABILITIES.RESPONSIBILITYVECTOR, values);
    }

    /**
     * Fetch records that have <code>OtherActors IN (values)</code>
     */
    public List<gov.nist.csrk.jooq.tables.pojos.Capabilities> fetchByOtheractors(String... values) {
        return fetch(Capabilities.CAPABILITIES.OTHERACTORS, values);
    }
}
