/*
 * This file is generated by jOOQ.
*/
package gov.nist.csrk.jooq.tables.daos;


import gov.nist.csrk.jooq.tables.Families;
import gov.nist.csrk.jooq.tables.records.FamiliesRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FamiliesDao extends DAOImpl<FamiliesRecord, gov.nist.csrk.jooq.tables.pojos.Families, Integer> {

    /**
     * Create a new FamiliesDao without any configuration
     */
    public FamiliesDao() {
        super(Families.FAMILIES, gov.nist.csrk.jooq.tables.pojos.Families.class);
    }

    /**
     * Create a new FamiliesDao with an attached configuration
     */
    public FamiliesDao(Configuration configuration) {
        super(Families.FAMILIES, gov.nist.csrk.jooq.tables.pojos.Families.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(gov.nist.csrk.jooq.tables.pojos.Families object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>Id IN (values)</code>
     */
    public List<gov.nist.csrk.jooq.tables.pojos.Families> fetchById(Integer... values) {
        return fetch(Families.FAMILIES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>Id = value</code>
     */
    public gov.nist.csrk.jooq.tables.pojos.Families fetchOneById(Integer value) {
        return fetchOne(Families.FAMILIES.ID, value);
    }

    /**
     * Fetch records that have <code>Name IN (values)</code>
     */
    public List<gov.nist.csrk.jooq.tables.pojos.Families> fetchByName(String... values) {
        return fetch(Families.FAMILIES.NAME, values);
    }

    /**
     * Fetch records that have <code>Description IN (values)</code>
     */
    public List<gov.nist.csrk.jooq.tables.pojos.Families> fetchByDescription(String... values) {
        return fetch(Families.FAMILIES.DESCRIPTION, values);
    }
}
