/*
 * This file is generated by jOOQ.
*/
package gov.nist.csrc.jooq.tables.daos;


import gov.nist.csrc.jooq.tables.Controls;
import gov.nist.csrc.jooq.tables.records.ControlsRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ControlsDao extends DAOImpl<ControlsRecord, gov.nist.csrc.jooq.tables.pojos.Controls, Integer> {

    /**
     * Create a new ControlsDao without any configuration
     */
    public ControlsDao() {
        super(Controls.CONTROLS, gov.nist.csrc.jooq.tables.pojos.Controls.class);
    }

    /**
     * Create a new ControlsDao with an attached configuration
     */
    public ControlsDao(Configuration configuration) {
        super(Controls.CONTROLS, gov.nist.csrc.jooq.tables.pojos.Controls.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(gov.nist.csrc.jooq.tables.pojos.Controls object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>Id IN (values)</code>
     */
    public List<gov.nist.csrc.jooq.tables.pojos.Controls> fetchById(Integer... values) {
        return fetch(Controls.CONTROLS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>Id = value</code>
     */
    public gov.nist.csrc.jooq.tables.pojos.Controls fetchOneById(Integer value) {
        return fetchOne(Controls.CONTROLS.ID, value);
    }

    /**
     * Fetch records that have <code>Name IN (values)</code>
     */
    public List<gov.nist.csrc.jooq.tables.pojos.Controls> fetchByName(String... values) {
        return fetch(Controls.CONTROLS.NAME, values);
    }

    /**
     * Fetch records that have <code>BaselineId IN (values)</code>
     */
    public List<gov.nist.csrc.jooq.tables.pojos.Controls> fetchByBaselineid(Integer... values) {
        return fetch(Controls.CONTROLS.BASELINEID, values);
    }

    /**
     * Fetch records that have <code>FamilyId IN (values)</code>
     */
    public List<gov.nist.csrc.jooq.tables.pojos.Controls> fetchByFamilyid(Integer... values) {
        return fetch(Controls.CONTROLS.FAMILYID, values);
    }

    /**
     * Fetch records that have <code>PriorityId IN (values)</code>
     */
    public List<gov.nist.csrc.jooq.tables.pojos.Controls> fetchByPriorityid(Integer... values) {
        return fetch(Controls.CONTROLS.PRIORITYID, values);
    }

    /**
     * Fetch records that have <code>Description IN (values)</code>
     */
    public List<gov.nist.csrc.jooq.tables.pojos.Controls> fetchByDescription(String... values) {
        return fetch(Controls.CONTROLS.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>Guidance IN (values)</code>
     */
    public List<gov.nist.csrc.jooq.tables.pojos.Controls> fetchByGuidance(String... values) {
        return fetch(Controls.CONTROLS.GUIDANCE, values);
    }
}
