/*
 * This file is generated by jOOQ.
*/
package gov.nist.csrc.jooq.tables.daos;


import gov.nist.csrc.jooq.tables.Priorities;
import gov.nist.csrc.jooq.tables.records.PrioritiesRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrioritiesDao extends DAOImpl<PrioritiesRecord, gov.nist.csrc.jooq.tables.pojos.Priorities, Integer> {

    /**
     * Create a new PrioritiesDao without any configuration
     */
    public PrioritiesDao() {
        super(Priorities.PRIORITIES, gov.nist.csrc.jooq.tables.pojos.Priorities.class);
    }

    /**
     * Create a new PrioritiesDao with an attached configuration
     */
    public PrioritiesDao(Configuration configuration) {
        super(Priorities.PRIORITIES, gov.nist.csrc.jooq.tables.pojos.Priorities.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(gov.nist.csrc.jooq.tables.pojos.Priorities object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>Id IN (values)</code>
     */
    public List<gov.nist.csrc.jooq.tables.pojos.Priorities> fetchById(Integer... values) {
        return fetch(Priorities.PRIORITIES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>Id = value</code>
     */
    public gov.nist.csrc.jooq.tables.pojos.Priorities fetchOneById(Integer value) {
        return fetchOne(Priorities.PRIORITIES.ID, value);
    }

    /**
     * Fetch records that have <code>Name IN (values)</code>
     */
    public List<gov.nist.csrc.jooq.tables.pojos.Priorities> fetchByName(String... values) {
        return fetch(Priorities.PRIORITIES.NAME, values);
    }

    /**
     * Fetch records that have <code>Description IN (values)</code>
     */
    public List<gov.nist.csrc.jooq.tables.pojos.Priorities> fetchByDescription(String... values) {
        return fetch(Priorities.PRIORITIES.DESCRIPTION, values);
    }
}
