/*
 * This file is generated by jOOQ.
*/
package gov.nist.csrc.jooq.tables.daos;


import gov.nist.csrc.jooq.tables.Specs;
import gov.nist.csrc.jooq.tables.records.SpecsRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpecsDao extends DAOImpl<SpecsRecord, gov.nist.csrc.jooq.tables.pojos.Specs, Integer> {

    /**
     * Create a new SpecsDao without any configuration
     */
    public SpecsDao() {
        super(Specs.SPECS, gov.nist.csrc.jooq.tables.pojos.Specs.class);
    }

    /**
     * Create a new SpecsDao with an attached configuration
     */
    public SpecsDao(Configuration configuration) {
        super(Specs.SPECS, gov.nist.csrc.jooq.tables.pojos.Specs.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(gov.nist.csrc.jooq.tables.pojos.Specs object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>Id IN (values)</code>
     */
    public List<gov.nist.csrc.jooq.tables.pojos.Specs> fetchById(Integer... values) {
        return fetch(Specs.SPECS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>Id = value</code>
     */
    public gov.nist.csrc.jooq.tables.pojos.Specs fetchOneById(Integer value) {
        return fetchOne(Specs.SPECS.ID, value);
    }

    /**
     * Fetch records that have <code>ControlsId IN (values)</code>
     */
    public List<gov.nist.csrc.jooq.tables.pojos.Specs> fetchByControlsid(Integer... values) {
        return fetch(Specs.SPECS.CONTROLSID, values);
    }

    /**
     * Fetch records that have <code>SpecificationName IN (values)</code>
     */
    public List<gov.nist.csrc.jooq.tables.pojos.Specs> fetchBySpecificationname(String... values) {
        return fetch(Specs.SPECS.SPECIFICATIONNAME, values);
    }

    /**
     * Fetch records that have <code>Description IN (values)</code>
     */
    public List<gov.nist.csrc.jooq.tables.pojos.Specs> fetchByDescription(String... values) {
        return fetch(Specs.SPECS.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>Guidance IN (values)</code>
     */
    public List<gov.nist.csrc.jooq.tables.pojos.Specs> fetchByGuidance(String... values) {
        return fetch(Specs.SPECS.GUIDANCE, values);
    }
}
