/*
 * This file is generated by jOOQ.
*/
package gov.nist.csrc.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SqliteSequence implements Serializable {

    private static final long serialVersionUID = -1220238437;

    private Object name;
    private Object seq;

    public SqliteSequence() {}

    public SqliteSequence(SqliteSequence value) {
        this.name = value.name;
        this.seq = value.seq;
    }

    public SqliteSequence(
        Object name,
        Object seq
    ) {
        this.name = name;
        this.seq = seq;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getName() {
        return this.name;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setName(Object name) {
        this.name = name;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getSeq() {
        return this.seq;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setSeq(Object seq) {
        this.seq = seq;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SqliteSequence (");

        sb.append(name);
        sb.append(", ").append(seq);

        sb.append(")");
        return sb.toString();
    }
}
