/*
 * This file is generated by jOOQ.
*/
package gov.nist.csrc.jooq.tables.records;


import gov.nist.csrc.jooq.tables.Capabilities;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CapabilitiesRecord extends UpdatableRecordImpl<CapabilitiesRecord> implements Record15<Integer, String, String, String, String, String, String, String, String, String, Integer, Integer, Integer, String, String> {

    private static final long serialVersionUID = 1751187169;

    /**
     * Setter for <code>Capabilities.Id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Capabilities.Id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Capabilities.Domain</code>.
     */
    public void setDomain(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Capabilities.Domain</code>.
     */
    public String getDomain() {
        return (String) get(1);
    }

    /**
     * Setter for <code>Capabilities.Container</code>.
     */
    public void setContainer(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>Capabilities.Container</code>.
     */
    public String getContainer() {
        return (String) get(2);
    }

    /**
     * Setter for <code>Capabilities.Capability</code>.
     */
    public void setCapability(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>Capabilities.Capability</code>.
     */
    public String getCapability() {
        return (String) get(3);
    }

    /**
     * Setter for <code>Capabilities.Capability2</code>.
     */
    public void setCapability2(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>Capabilities.Capability2</code>.
     */
    public String getCapability2() {
        return (String) get(4);
    }

    /**
     * Setter for <code>Capabilities.UniqueId</code>.
     */
    public void setUniqueid(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>Capabilities.UniqueId</code>.
     */
    public String getUniqueid() {
        return (String) get(5);
    }

    /**
     * Setter for <code>Capabilities.Description</code>.
     */
    public void setDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>Capabilities.Description</code>.
     */
    public String getDescription() {
        return (String) get(6);
    }

    /**
     * Setter for <code>Capabilities.CSADescription</code>.
     */
    public void setCsadescription(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>Capabilities.CSADescription</code>.
     */
    public String getCsadescription() {
        return (String) get(7);
    }

    /**
     * Setter for <code>Capabilities.Notes</code>.
     */
    public void setNotes(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>Capabilities.Notes</code>.
     */
    public String getNotes() {
        return (String) get(8);
    }

    /**
     * Setter for <code>Capabilities.Scopes</code>.
     */
    public void setScopes(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>Capabilities.Scopes</code>.
     */
    public String getScopes() {
        return (String) get(9);
    }

    /**
     * Setter for <code>Capabilities.C</code>.
     */
    public void setC(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>Capabilities.C</code>.
     */
    public Integer getC() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>Capabilities.I</code>.
     */
    public void setI(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>Capabilities.I</code>.
     */
    public Integer getI() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>Capabilities.A</code>.
     */
    public void setA(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>Capabilities.A</code>.
     */
    public Integer getA() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>Capabilities.ResponsibilityVector</code>.
     */
    public void setResponsibilityvector(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>Capabilities.ResponsibilityVector</code>.
     */
    public String getResponsibilityvector() {
        return (String) get(13);
    }

    /**
     * Setter for <code>Capabilities.OtherActors</code>.
     */
    public void setOtheractors(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>Capabilities.OtherActors</code>.
     */
    public String getOtheractors() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, String, String, String, String, String, String, String, String, String, Integer, Integer, Integer, String, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, String, String, String, String, String, String, String, String, String, Integer, Integer, Integer, String, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Capabilities.CAPABILITIES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Capabilities.CAPABILITIES.DOMAIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Capabilities.CAPABILITIES.CONTAINER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Capabilities.CAPABILITIES.CAPABILITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Capabilities.CAPABILITIES.CAPABILITY2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Capabilities.CAPABILITIES.UNIQUEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Capabilities.CAPABILITIES.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Capabilities.CAPABILITIES.CSADESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Capabilities.CAPABILITIES.NOTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Capabilities.CAPABILITIES.SCOPES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return Capabilities.CAPABILITIES.C;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return Capabilities.CAPABILITIES.I;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return Capabilities.CAPABILITIES.A;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Capabilities.CAPABILITIES.RESPONSIBILITYVECTOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return Capabilities.CAPABILITIES.OTHERACTORS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getDomain();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getContainer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCapability();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCapability2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getUniqueid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getCsadescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getNotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getScopes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getC();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component12() {
        return getI();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component13() {
        return getA();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getResponsibilityvector();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getOtheractors();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDomain();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getContainer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCapability();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCapability2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUniqueid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCsadescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getNotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getScopes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getC();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getI();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getA();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getResponsibilityvector();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getOtheractors();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CapabilitiesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CapabilitiesRecord value2(String value) {
        setDomain(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CapabilitiesRecord value3(String value) {
        setContainer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CapabilitiesRecord value4(String value) {
        setCapability(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CapabilitiesRecord value5(String value) {
        setCapability2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CapabilitiesRecord value6(String value) {
        setUniqueid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CapabilitiesRecord value7(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CapabilitiesRecord value8(String value) {
        setCsadescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CapabilitiesRecord value9(String value) {
        setNotes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CapabilitiesRecord value10(String value) {
        setScopes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CapabilitiesRecord value11(Integer value) {
        setC(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CapabilitiesRecord value12(Integer value) {
        setI(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CapabilitiesRecord value13(Integer value) {
        setA(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CapabilitiesRecord value14(String value) {
        setResponsibilityvector(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CapabilitiesRecord value15(String value) {
        setOtheractors(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CapabilitiesRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, Integer value11, Integer value12, Integer value13, String value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CapabilitiesRecord
     */
    public CapabilitiesRecord() {
        super(Capabilities.CAPABILITIES);
    }

    /**
     * Create a detached, initialised CapabilitiesRecord
     */
    public CapabilitiesRecord(Integer id, String domain, String container, String capability, String capability2, String uniqueid, String description, String csadescription, String notes, String scopes, Integer c, Integer i, Integer a, String responsibilityvector, String otheractors) {
        super(Capabilities.CAPABILITIES);

        set(0, id);
        set(1, domain);
        set(2, container);
        set(3, capability);
        set(4, capability2);
        set(5, uniqueid);
        set(6, description);
        set(7, csadescription);
        set(8, notes);
        set(9, scopes);
        set(10, c);
        set(11, i);
        set(12, a);
        set(13, responsibilityvector);
        set(14, otheractors);
    }
}
