/*
 * This file is generated by jOOQ.
*/
package gov.nist.csrc.jooq.tables.records;


import gov.nist.csrc.jooq.tables.Baselines;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BaselinesRecord extends UpdatableRecordImpl<BaselinesRecord> implements Record5<Integer, Boolean, Boolean, Boolean, String> {

    private static final long serialVersionUID = 1697717810;

    /**
     * Setter for <code>Baselines.Id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Baselines.Id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Baselines.ImpactLow</code>.
     */
    public void setImpactlow(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>Baselines.ImpactLow</code>.
     */
    public Boolean getImpactlow() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>Baselines.ImpactModerate</code>.
     */
    public void setImpactmoderate(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>Baselines.ImpactModerate</code>.
     */
    public Boolean getImpactmoderate() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>Baselines.ImpactHigh</code>.
     */
    public void setImpacthigh(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>Baselines.ImpactHigh</code>.
     */
    public Boolean getImpacthigh() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>Baselines.Description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>Baselines.Description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Boolean, Boolean, Boolean, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Boolean, Boolean, Boolean, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Baselines.BASELINES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field2() {
        return Baselines.BASELINES.IMPACTLOW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field3() {
        return Baselines.BASELINES.IMPACTMODERATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return Baselines.BASELINES.IMPACTHIGH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Baselines.BASELINES.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component2() {
        return getImpactlow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component3() {
        return getImpactmoderate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getImpacthigh();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value2() {
        return getImpactlow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value3() {
        return getImpactmoderate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getImpacthigh();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BaselinesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BaselinesRecord value2(Boolean value) {
        setImpactlow(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BaselinesRecord value3(Boolean value) {
        setImpactmoderate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BaselinesRecord value4(Boolean value) {
        setImpacthigh(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BaselinesRecord value5(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BaselinesRecord values(Integer value1, Boolean value2, Boolean value3, Boolean value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BaselinesRecord
     */
    public BaselinesRecord() {
        super(Baselines.BASELINES);
    }

    /**
     * Create a detached, initialised BaselinesRecord
     */
    public BaselinesRecord(Integer id, Boolean impactlow, Boolean impactmoderate, Boolean impacthigh, String description) {
        super(Baselines.BASELINES);

        set(0, id);
        set(1, impactlow);
        set(2, impactmoderate);
        set(3, impacthigh);
        set(4, description);
    }
}
