/*
 * This file is generated by jOOQ.
*/
package gov.nist.csrc.jooq.tables.records;


import gov.nist.csrc.jooq.tables.Ticmappings;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TicmappingsRecord extends UpdatableRecordImpl<TicmappingsRecord> implements Record3<Integer, Integer, String> {

    private static final long serialVersionUID = 1500699843;

    /**
     * Setter for <code>TICMappings.Id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>TICMappings.Id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>TICMappings.CapabilityId</code>.
     */
    public void setCapabilityid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>TICMappings.CapabilityId</code>.
     */
    public Integer getCapabilityid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>TICMappings.TICName</code>.
     */
    public void setTicname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>TICMappings.TICName</code>.
     */
    public String getTicname() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Ticmappings.TICMAPPINGS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Ticmappings.TICMAPPINGS.CAPABILITYID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Ticmappings.TICMAPPINGS.TICNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getCapabilityid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTicname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCapabilityid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTicname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TicmappingsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TicmappingsRecord value2(Integer value) {
        setCapabilityid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TicmappingsRecord value3(String value) {
        setTicname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TicmappingsRecord values(Integer value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TicmappingsRecord
     */
    public TicmappingsRecord() {
        super(Ticmappings.TICMAPPINGS);
    }

    /**
     * Create a detached, initialised TicmappingsRecord
     */
    public TicmappingsRecord(Integer id, Integer capabilityid, String ticname) {
        super(Ticmappings.TICMAPPINGS);

        set(0, id);
        set(1, capabilityid);
        set(2, ticname);
    }
}
