/*
 * This file is generated by jOOQ.
*/
package gov.nist.csrk.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Relateds implements Serializable {

    private static final long serialVersionUID = 1987697650;

    private Integer id;
    private Integer parentid;
    private Integer childid;

    public Relateds() {}

    public Relateds(Relateds value) {
        this.id = value.id;
        this.parentid = value.parentid;
        this.childid = value.childid;
    }

    public Relateds(
        Integer id,
        Integer parentid,
        Integer childid
    ) {
        this.id = id;
        this.parentid = parentid;
        this.childid = childid;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getParentid() {
        return this.parentid;
    }

    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    public Integer getChildid() {
        return this.childid;
    }

    public void setChildid(Integer childid) {
        this.childid = childid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Relateds (");

        sb.append(id);
        sb.append(", ").append(parentid);
        sb.append(", ").append(childid);

        sb.append(")");
        return sb.toString();
    }
}
