/*
 * This file is generated by jOOQ.
*/
package gov.nist.csrk.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ticmappings implements Serializable {

    private static final long serialVersionUID = -295535122;

    private Integer id;
    private Integer capabilityid;
    private String  ticname;

    public Ticmappings() {}

    public Ticmappings(Ticmappings value) {
        this.id = value.id;
        this.capabilityid = value.capabilityid;
        this.ticname = value.ticname;
    }

    public Ticmappings(
        Integer id,
        Integer capabilityid,
        String  ticname
    ) {
        this.id = id;
        this.capabilityid = capabilityid;
        this.ticname = ticname;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCapabilityid() {
        return this.capabilityid;
    }

    public void setCapabilityid(Integer capabilityid) {
        this.capabilityid = capabilityid;
    }

    public String getTicname() {
        return this.ticname;
    }

    public void setTicname(String ticname) {
        this.ticname = ticname;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Ticmappings (");

        sb.append(id);
        sb.append(", ").append(capabilityid);
        sb.append(", ").append(ticname);

        sb.append(")");
        return sb.toString();
    }
}
