/*
 * This file is generated by jOOQ.
*/
package gov.nist.csrc.jooq.tables.daos;


import gov.nist.csrc.jooq.tables.Baselines;
import gov.nist.csrc.jooq.tables.records.BaselinesRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BaselinesDao extends DAOImpl<BaselinesRecord, gov.nist.csrc.jooq.tables.pojos.Baselines, Integer> {

    /**
     * Create a new BaselinesDao without any configuration
     */
    public BaselinesDao() {
        super(Baselines.BASELINES, gov.nist.csrc.jooq.tables.pojos.Baselines.class);
    }

    /**
     * Create a new BaselinesDao with an attached configuration
     */
    public BaselinesDao(Configuration configuration) {
        super(Baselines.BASELINES, gov.nist.csrc.jooq.tables.pojos.Baselines.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(gov.nist.csrc.jooq.tables.pojos.Baselines object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>Id IN (values)</code>
     */
    public List<gov.nist.csrc.jooq.tables.pojos.Baselines> fetchById(Integer... values) {
        return fetch(Baselines.BASELINES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>Id = value</code>
     */
    public gov.nist.csrc.jooq.tables.pojos.Baselines fetchOneById(Integer value) {
        return fetchOne(Baselines.BASELINES.ID, value);
    }

    /**
     * Fetch records that have <code>ImpactLow IN (values)</code>
     */
    public List<gov.nist.csrc.jooq.tables.pojos.Baselines> fetchByImpactlow(Boolean... values) {
        return fetch(Baselines.BASELINES.IMPACTLOW, values);
    }

    /**
     * Fetch records that have <code>ImpactModerate IN (values)</code>
     */
    public List<gov.nist.csrc.jooq.tables.pojos.Baselines> fetchByImpactmoderate(Boolean... values) {
        return fetch(Baselines.BASELINES.IMPACTMODERATE, values);
    }

    /**
     * Fetch records that have <code>ImpactHigh IN (values)</code>
     */
    public List<gov.nist.csrc.jooq.tables.pojos.Baselines> fetchByImpacthigh(Boolean... values) {
        return fetch(Baselines.BASELINES.IMPACTHIGH, values);
    }

    /**
     * Fetch records that have <code>Description IN (values)</code>
     */
    public List<gov.nist.csrc.jooq.tables.pojos.Baselines> fetchByDescription(String... values) {
        return fetch(Baselines.BASELINES.DESCRIPTION, values);
    }
}
