/*
 * This file is generated by jOOQ.
*/
package gov.nist.csrc.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Baselinesecuritymappings implements Serializable {

    private static final long serialVersionUID = -22927041;

    private Integer id;
    private Integer level;
    private Integer baselineauthor;
    private Boolean iscontrolmap;
    private Integer specsid;
    private Integer controlsid;

    public Baselinesecuritymappings() {}

    public Baselinesecuritymappings(Baselinesecuritymappings value) {
        this.id = value.id;
        this.level = value.level;
        this.baselineauthor = value.baselineauthor;
        this.iscontrolmap = value.iscontrolmap;
        this.specsid = value.specsid;
        this.controlsid = value.controlsid;
    }

    public Baselinesecuritymappings(
        Integer id,
        Integer level,
        Integer baselineauthor,
        Boolean iscontrolmap,
        Integer specsid,
        Integer controlsid
    ) {
        this.id = id;
        this.level = level;
        this.baselineauthor = baselineauthor;
        this.iscontrolmap = iscontrolmap;
        this.specsid = specsid;
        this.controlsid = controlsid;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getLevel() {
        return this.level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public Integer getBaselineauthor() {
        return this.baselineauthor;
    }

    public void setBaselineauthor(Integer baselineauthor) {
        this.baselineauthor = baselineauthor;
    }

    public Boolean getIscontrolmap() {
        return this.iscontrolmap;
    }

    public void setIscontrolmap(Boolean iscontrolmap) {
        this.iscontrolmap = iscontrolmap;
    }

    public Integer getSpecsid() {
        return this.specsid;
    }

    public void setSpecsid(Integer specsid) {
        this.specsid = specsid;
    }

    public Integer getControlsid() {
        return this.controlsid;
    }

    public void setControlsid(Integer controlsid) {
        this.controlsid = controlsid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Baselinesecuritymappings (");

        sb.append(id);
        sb.append(", ").append(level);
        sb.append(", ").append(baselineauthor);
        sb.append(", ").append(iscontrolmap);
        sb.append(", ").append(specsid);
        sb.append(", ").append(controlsid);

        sb.append(")");
        return sb.toString();
    }
}
