/*
 * This file is generated by jOOQ.
*/
package gov.nist.csrc.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Capabilities implements Serializable {

    private static final long serialVersionUID = -771347848;

    private Integer id;
    private String  domain;
    private String  container;
    private String  capability;
    private String  capability2;
    private String  uniqueid;
    private String  description;
    private String  csadescription;
    private String  notes;
    private String  scopes;
    private Integer c;
    private Integer i;
    private Integer a;
    private String  responsibilityvector;
    private String  otheractors;

    public Capabilities() {}

    public Capabilities(Capabilities value) {
        this.id = value.id;
        this.domain = value.domain;
        this.container = value.container;
        this.capability = value.capability;
        this.capability2 = value.capability2;
        this.uniqueid = value.uniqueid;
        this.description = value.description;
        this.csadescription = value.csadescription;
        this.notes = value.notes;
        this.scopes = value.scopes;
        this.c = value.c;
        this.i = value.i;
        this.a = value.a;
        this.responsibilityvector = value.responsibilityvector;
        this.otheractors = value.otheractors;
    }

    public Capabilities(
        Integer id,
        String  domain,
        String  container,
        String  capability,
        String  capability2,
        String  uniqueid,
        String  description,
        String  csadescription,
        String  notes,
        String  scopes,
        Integer c,
        Integer i,
        Integer a,
        String  responsibilityvector,
        String  otheractors
    ) {
        this.id = id;
        this.domain = domain;
        this.container = container;
        this.capability = capability;
        this.capability2 = capability2;
        this.uniqueid = uniqueid;
        this.description = description;
        this.csadescription = csadescription;
        this.notes = notes;
        this.scopes = scopes;
        this.c = c;
        this.i = i;
        this.a = a;
        this.responsibilityvector = responsibilityvector;
        this.otheractors = otheractors;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getDomain() {
        return this.domain;
    }

    public void setDomain(String domain) {
        this.domain = domain;
    }

    public String getContainer() {
        return this.container;
    }

    public void setContainer(String container) {
        this.container = container;
    }

    public String getCapability() {
        return this.capability;
    }

    public void setCapability(String capability) {
        this.capability = capability;
    }

    public String getCapability2() {
        return this.capability2;
    }

    public void setCapability2(String capability2) {
        this.capability2 = capability2;
    }

    public String getUniqueid() {
        return this.uniqueid;
    }

    public void setUniqueid(String uniqueid) {
        this.uniqueid = uniqueid;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCsadescription() {
        return this.csadescription;
    }

    public void setCsadescription(String csadescription) {
        this.csadescription = csadescription;
    }

    public String getNotes() {
        return this.notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public String getScopes() {
        return this.scopes;
    }

    public void setScopes(String scopes) {
        this.scopes = scopes;
    }

    public Integer getC() {
        return this.c;
    }

    public void setC(Integer c) {
        this.c = c;
    }

    public Integer getI() {
        return this.i;
    }

    public void setI(Integer i) {
        this.i = i;
    }

    public Integer getA() {
        return this.a;
    }

    public void setA(Integer a) {
        this.a = a;
    }

    public String getResponsibilityvector() {
        return this.responsibilityvector;
    }

    public void setResponsibilityvector(String responsibilityvector) {
        this.responsibilityvector = responsibilityvector;
    }

    public String getOtheractors() {
        return this.otheractors;
    }

    public void setOtheractors(String otheractors) {
        this.otheractors = otheractors;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Capabilities (");

        sb.append(id);
        sb.append(", ").append(domain);
        sb.append(", ").append(container);
        sb.append(", ").append(capability);
        sb.append(", ").append(capability2);
        sb.append(", ").append(uniqueid);
        sb.append(", ").append(description);
        sb.append(", ").append(csadescription);
        sb.append(", ").append(notes);
        sb.append(", ").append(scopes);
        sb.append(", ").append(c);
        sb.append(", ").append(i);
        sb.append(", ").append(a);
        sb.append(", ").append(responsibilityvector);
        sb.append(", ").append(otheractors);

        sb.append(")");
        return sb.toString();
    }
}
