/*
 * This file is generated by jOOQ.
*/
package gov.nist.csrc.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Maptypescapabilitiescontrols implements Serializable {

    private static final long serialVersionUID = 1689298886;

    private Integer id;
    private Integer capabilitiesid;
    private Integer controlsid;
    private Integer maptypesid;
    private Integer specsid;
    private Boolean iscontrolmap;

    public Maptypescapabilitiescontrols() {}

    public Maptypescapabilitiescontrols(Maptypescapabilitiescontrols value) {
        this.id = value.id;
        this.capabilitiesid = value.capabilitiesid;
        this.controlsid = value.controlsid;
        this.maptypesid = value.maptypesid;
        this.specsid = value.specsid;
        this.iscontrolmap = value.iscontrolmap;
    }

    public Maptypescapabilitiescontrols(
        Integer id,
        Integer capabilitiesid,
        Integer controlsid,
        Integer maptypesid,
        Integer specsid,
        Boolean iscontrolmap
    ) {
        this.id = id;
        this.capabilitiesid = capabilitiesid;
        this.controlsid = controlsid;
        this.maptypesid = maptypesid;
        this.specsid = specsid;
        this.iscontrolmap = iscontrolmap;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCapabilitiesid() {
        return this.capabilitiesid;
    }

    public void setCapabilitiesid(Integer capabilitiesid) {
        this.capabilitiesid = capabilitiesid;
    }

    public Integer getControlsid() {
        return this.controlsid;
    }

    public void setControlsid(Integer controlsid) {
        this.controlsid = controlsid;
    }

    public Integer getMaptypesid() {
        return this.maptypesid;
    }

    public void setMaptypesid(Integer maptypesid) {
        this.maptypesid = maptypesid;
    }

    public Integer getSpecsid() {
        return this.specsid;
    }

    public void setSpecsid(Integer specsid) {
        this.specsid = specsid;
    }

    public Boolean getIscontrolmap() {
        return this.iscontrolmap;
    }

    public void setIscontrolmap(Boolean iscontrolmap) {
        this.iscontrolmap = iscontrolmap;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Maptypescapabilitiescontrols (");

        sb.append(id);
        sb.append(", ").append(capabilitiesid);
        sb.append(", ").append(controlsid);
        sb.append(", ").append(maptypesid);
        sb.append(", ").append(specsid);
        sb.append(", ").append(iscontrolmap);

        sb.append(")");
        return sb.toString();
    }
}
