/*
 * This file is generated by jOOQ.
*/
package gov.nist.csrc.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Specs implements Serializable {

    private static final long serialVersionUID = 961132387;

    private Integer id;
    private Integer controlsid;
    private String  specificationname;
    private String  description;
    private String  guidance;

    public Specs() {}

    public Specs(Specs value) {
        this.id = value.id;
        this.controlsid = value.controlsid;
        this.specificationname = value.specificationname;
        this.description = value.description;
        this.guidance = value.guidance;
    }

    public Specs(
        Integer id,
        Integer controlsid,
        String  specificationname,
        String  description,
        String  guidance
    ) {
        this.id = id;
        this.controlsid = controlsid;
        this.specificationname = specificationname;
        this.description = description;
        this.guidance = guidance;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getControlsid() {
        return this.controlsid;
    }

    public void setControlsid(Integer controlsid) {
        this.controlsid = controlsid;
    }

    public String getSpecificationname() {
        return this.specificationname;
    }

    public void setSpecificationname(String specificationname) {
        this.specificationname = specificationname;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getGuidance() {
        return this.guidance;
    }

    public void setGuidance(String guidance) {
        this.guidance = guidance;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Specs (");

        sb.append(id);
        sb.append(", ").append(controlsid);
        sb.append(", ").append(specificationname);
        sb.append(", ").append(description);
        sb.append(", ").append(guidance);

        sb.append(")");
        return sb.toString();
    }
}
