/*
 * This file is generated by jOOQ.
*/
package gov.nist.csrc.jooq;


import gov.nist.csrc.jooq.tables.Baselines;
import gov.nist.csrc.jooq.tables.Baselinesecuritymappings;
import gov.nist.csrc.jooq.tables.Capabilities;
import gov.nist.csrc.jooq.tables.Controls;
import gov.nist.csrc.jooq.tables.Families;
import gov.nist.csrc.jooq.tables.Maptypescapabilitiescontrols;
import gov.nist.csrc.jooq.tables.Priorities;
import gov.nist.csrc.jooq.tables.Relateds;
import gov.nist.csrc.jooq.tables.Specs;
import gov.nist.csrc.jooq.tables.Ticmappings;
import gov.nist.csrc.jooq.tables.records.BaselinesRecord;
import gov.nist.csrc.jooq.tables.records.BaselinesecuritymappingsRecord;
import gov.nist.csrc.jooq.tables.records.CapabilitiesRecord;
import gov.nist.csrc.jooq.tables.records.ControlsRecord;
import gov.nist.csrc.jooq.tables.records.FamiliesRecord;
import gov.nist.csrc.jooq.tables.records.MaptypescapabilitiescontrolsRecord;
import gov.nist.csrc.jooq.tables.records.PrioritiesRecord;
import gov.nist.csrc.jooq.tables.records.RelatedsRecord;
import gov.nist.csrc.jooq.tables.records.SpecsRecord;
import gov.nist.csrc.jooq.tables.records.TicmappingsRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BaselinesecuritymappingsRecord> PK_BASELINESECURITYMAPPINGS = UniqueKeys0.PK_BASELINESECURITYMAPPINGS;
    public static final UniqueKey<BaselinesRecord> PK_BASELINES = UniqueKeys0.PK_BASELINES;
    public static final UniqueKey<CapabilitiesRecord> PK_CAPABILITIES = UniqueKeys0.PK_CAPABILITIES;
    public static final UniqueKey<ControlsRecord> PK_CONTROLS = UniqueKeys0.PK_CONTROLS;
    public static final UniqueKey<FamiliesRecord> PK_FAMILIES = UniqueKeys0.PK_FAMILIES;
    public static final UniqueKey<MaptypescapabilitiescontrolsRecord> PK_MAPTYPESCAPABILITIESCONTROLS = UniqueKeys0.PK_MAPTYPESCAPABILITIESCONTROLS;
    public static final UniqueKey<PrioritiesRecord> PK_PRIORITIES = UniqueKeys0.PK_PRIORITIES;
    public static final UniqueKey<RelatedsRecord> PK_RELATEDS = UniqueKeys0.PK_RELATEDS;
    public static final UniqueKey<SpecsRecord> PK_SPECS = UniqueKeys0.PK_SPECS;
    public static final UniqueKey<TicmappingsRecord> PK_TICMAPPINGS = UniqueKeys0.PK_TICMAPPINGS;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BaselinesecuritymappingsRecord, SpecsRecord> FK_BASELINESECURITYMAPPINGS_SPECS_1 = ForeignKeys0.FK_BASELINESECURITYMAPPINGS_SPECS_1;
    public static final ForeignKey<BaselinesecuritymappingsRecord, ControlsRecord> FK_BASELINESECURITYMAPPINGS_CONTROLS_1 = ForeignKeys0.FK_BASELINESECURITYMAPPINGS_CONTROLS_1;
    public static final ForeignKey<ControlsRecord, BaselinesRecord> FK_CONTROLS_BASELINES_1 = ForeignKeys0.FK_CONTROLS_BASELINES_1;
    public static final ForeignKey<ControlsRecord, FamiliesRecord> FK_CONTROLS_FAMILIES_1 = ForeignKeys0.FK_CONTROLS_FAMILIES_1;
    public static final ForeignKey<ControlsRecord, PrioritiesRecord> FK_CONTROLS_PRIORITIES_1 = ForeignKeys0.FK_CONTROLS_PRIORITIES_1;
    public static final ForeignKey<MaptypescapabilitiescontrolsRecord, CapabilitiesRecord> FK_MAPTYPESCAPABILITIESCONTROLS_CAPABILITIES_1 = ForeignKeys0.FK_MAPTYPESCAPABILITIESCONTROLS_CAPABILITIES_1;
    public static final ForeignKey<MaptypescapabilitiescontrolsRecord, ControlsRecord> FK_MAPTYPESCAPABILITIESCONTROLS_CONTROLS_1 = ForeignKeys0.FK_MAPTYPESCAPABILITIESCONTROLS_CONTROLS_1;
    public static final ForeignKey<MaptypescapabilitiescontrolsRecord, SpecsRecord> FK_MAPTYPESCAPABILITIESCONTROLS_SPECS_1 = ForeignKeys0.FK_MAPTYPESCAPABILITIESCONTROLS_SPECS_1;
    public static final ForeignKey<RelatedsRecord, ControlsRecord> FK_RELATEDS_CONTROLS_2 = ForeignKeys0.FK_RELATEDS_CONTROLS_2;
    public static final ForeignKey<RelatedsRecord, ControlsRecord> FK_RELATEDS_CONTROLS_1 = ForeignKeys0.FK_RELATEDS_CONTROLS_1;
    public static final ForeignKey<SpecsRecord, ControlsRecord> FK_SPECS_CONTROLS_1 = ForeignKeys0.FK_SPECS_CONTROLS_1;
    public static final ForeignKey<TicmappingsRecord, CapabilitiesRecord> FK_TICMAPPINGS_CAPABILITIES_1 = ForeignKeys0.FK_TICMAPPINGS_CAPABILITIES_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<BaselinesecuritymappingsRecord> PK_BASELINESECURITYMAPPINGS = createUniqueKey(Baselinesecuritymappings.BASELINESECURITYMAPPINGS, "pk_BaselineSecurityMappings", Baselinesecuritymappings.BASELINESECURITYMAPPINGS.ID);
        public static final UniqueKey<BaselinesRecord> PK_BASELINES = createUniqueKey(Baselines.BASELINES, "pk_Baselines", Baselines.BASELINES.ID);
        public static final UniqueKey<CapabilitiesRecord> PK_CAPABILITIES = createUniqueKey(Capabilities.CAPABILITIES, "pk_Capabilities", Capabilities.CAPABILITIES.ID);
        public static final UniqueKey<ControlsRecord> PK_CONTROLS = createUniqueKey(Controls.CONTROLS, "pk_Controls", Controls.CONTROLS.ID);
        public static final UniqueKey<FamiliesRecord> PK_FAMILIES = createUniqueKey(Families.FAMILIES, "pk_Families", Families.FAMILIES.ID);
        public static final UniqueKey<MaptypescapabilitiescontrolsRecord> PK_MAPTYPESCAPABILITIESCONTROLS = createUniqueKey(Maptypescapabilitiescontrols.MAPTYPESCAPABILITIESCONTROLS, "pk_MapTypesCapabilitiesControls", Maptypescapabilitiescontrols.MAPTYPESCAPABILITIESCONTROLS.ID);
        public static final UniqueKey<PrioritiesRecord> PK_PRIORITIES = createUniqueKey(Priorities.PRIORITIES, "pk_Priorities", Priorities.PRIORITIES.ID);
        public static final UniqueKey<RelatedsRecord> PK_RELATEDS = createUniqueKey(Relateds.RELATEDS, "pk_Relateds", Relateds.RELATEDS.ID);
        public static final UniqueKey<SpecsRecord> PK_SPECS = createUniqueKey(Specs.SPECS, "pk_Specs", Specs.SPECS.ID);
        public static final UniqueKey<TicmappingsRecord> PK_TICMAPPINGS = createUniqueKey(Ticmappings.TICMAPPINGS, "pk_TICMappings", Ticmappings.TICMAPPINGS.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<BaselinesecuritymappingsRecord, SpecsRecord> FK_BASELINESECURITYMAPPINGS_SPECS_1 = createForeignKey(gov.nist.csrc.jooq.Keys.PK_SPECS, Baselinesecuritymappings.BASELINESECURITYMAPPINGS, "fk_BaselineSecurityMappings_Specs_1", Baselinesecuritymappings.BASELINESECURITYMAPPINGS.SPECSID);
        public static final ForeignKey<BaselinesecuritymappingsRecord, ControlsRecord> FK_BASELINESECURITYMAPPINGS_CONTROLS_1 = createForeignKey(gov.nist.csrc.jooq.Keys.PK_CONTROLS, Baselinesecuritymappings.BASELINESECURITYMAPPINGS, "fk_BaselineSecurityMappings_Controls_1", Baselinesecuritymappings.BASELINESECURITYMAPPINGS.CONTROLSID);
        public static final ForeignKey<ControlsRecord, BaselinesRecord> FK_CONTROLS_BASELINES_1 = createForeignKey(gov.nist.csrc.jooq.Keys.PK_BASELINES, Controls.CONTROLS, "fk_Controls_Baselines_1", Controls.CONTROLS.BASELINEID);
        public static final ForeignKey<ControlsRecord, FamiliesRecord> FK_CONTROLS_FAMILIES_1 = createForeignKey(gov.nist.csrc.jooq.Keys.PK_FAMILIES, Controls.CONTROLS, "fk_Controls_Families_1", Controls.CONTROLS.FAMILYID);
        public static final ForeignKey<ControlsRecord, PrioritiesRecord> FK_CONTROLS_PRIORITIES_1 = createForeignKey(gov.nist.csrc.jooq.Keys.PK_PRIORITIES, Controls.CONTROLS, "fk_Controls_Priorities_1", Controls.CONTROLS.PRIORITYID);
        public static final ForeignKey<MaptypescapabilitiescontrolsRecord, CapabilitiesRecord> FK_MAPTYPESCAPABILITIESCONTROLS_CAPABILITIES_1 = createForeignKey(gov.nist.csrc.jooq.Keys.PK_CAPABILITIES, Maptypescapabilitiescontrols.MAPTYPESCAPABILITIESCONTROLS, "fk_MapTypesCapabilitiesControls_Capabilities_1", Maptypescapabilitiescontrols.MAPTYPESCAPABILITIESCONTROLS.CAPABILITIESID);
        public static final ForeignKey<MaptypescapabilitiescontrolsRecord, ControlsRecord> FK_MAPTYPESCAPABILITIESCONTROLS_CONTROLS_1 = createForeignKey(gov.nist.csrc.jooq.Keys.PK_CONTROLS, Maptypescapabilitiescontrols.MAPTYPESCAPABILITIESCONTROLS, "fk_MapTypesCapabilitiesControls_Controls_1", Maptypescapabilitiescontrols.MAPTYPESCAPABILITIESCONTROLS.CONTROLSID);
        public static final ForeignKey<MaptypescapabilitiescontrolsRecord, SpecsRecord> FK_MAPTYPESCAPABILITIESCONTROLS_SPECS_1 = createForeignKey(gov.nist.csrc.jooq.Keys.PK_SPECS, Maptypescapabilitiescontrols.MAPTYPESCAPABILITIESCONTROLS, "fk_MapTypesCapabilitiesControls_Specs_1", Maptypescapabilitiescontrols.MAPTYPESCAPABILITIESCONTROLS.SPECSID);
        public static final ForeignKey<RelatedsRecord, ControlsRecord> FK_RELATEDS_CONTROLS_2 = createForeignKey(gov.nist.csrc.jooq.Keys.PK_CONTROLS, Relateds.RELATEDS, "fk_Relateds_Controls_2", Relateds.RELATEDS.PARENTID);
        public static final ForeignKey<RelatedsRecord, ControlsRecord> FK_RELATEDS_CONTROLS_1 = createForeignKey(gov.nist.csrc.jooq.Keys.PK_CONTROLS, Relateds.RELATEDS, "fk_Relateds_Controls_1", Relateds.RELATEDS.CHILDID);
        public static final ForeignKey<SpecsRecord, ControlsRecord> FK_SPECS_CONTROLS_1 = createForeignKey(gov.nist.csrc.jooq.Keys.PK_CONTROLS, Specs.SPECS, "fk_Specs_Controls_1", Specs.SPECS.CONTROLSID);
        public static final ForeignKey<TicmappingsRecord, CapabilitiesRecord> FK_TICMAPPINGS_CAPABILITIES_1 = createForeignKey(gov.nist.csrc.jooq.Keys.PK_CAPABILITIES, Ticmappings.TICMAPPINGS, "fk_TICMappings_Capabilities_1", Ticmappings.TICMAPPINGS.CAPABILITYID);
    }
}
