/*
 * This file is generated by jOOQ.
*/
package gov.nist.csrc.jooq;


import gov.nist.csrc.jooq.tables.Baselines;
import gov.nist.csrc.jooq.tables.Baselinesecuritymappings;
import gov.nist.csrc.jooq.tables.Capabilities;
import gov.nist.csrc.jooq.tables.Controls;
import gov.nist.csrc.jooq.tables.Families;
import gov.nist.csrc.jooq.tables.Maptypescapabilitiescontrols;
import gov.nist.csrc.jooq.tables.Priorities;
import gov.nist.csrc.jooq.tables.Relateds;
import gov.nist.csrc.jooq.tables.Specs;
import gov.nist.csrc.jooq.tables.SqliteSequence;
import gov.nist.csrc.jooq.tables.Ticmappings;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>BaselineSecurityMappings</code>.
     */
    public static final Baselinesecuritymappings BASELINESECURITYMAPPINGS = gov.nist.csrc.jooq.tables.Baselinesecuritymappings.BASELINESECURITYMAPPINGS;

    /**
     * The table <code>Baselines</code>.
     */
    public static final Baselines BASELINES = gov.nist.csrc.jooq.tables.Baselines.BASELINES;

    /**
     * The table <code>Capabilities</code>.
     */
    public static final Capabilities CAPABILITIES = gov.nist.csrc.jooq.tables.Capabilities.CAPABILITIES;

    /**
     * The table <code>Controls</code>.
     */
    public static final Controls CONTROLS = gov.nist.csrc.jooq.tables.Controls.CONTROLS;

    /**
     * The table <code>Families</code>.
     */
    public static final Families FAMILIES = gov.nist.csrc.jooq.tables.Families.FAMILIES;

    /**
     * The table <code>MapTypesCapabilitiesControls</code>.
     */
    public static final Maptypescapabilitiescontrols MAPTYPESCAPABILITIESCONTROLS = gov.nist.csrc.jooq.tables.Maptypescapabilitiescontrols.MAPTYPESCAPABILITIESCONTROLS;

    /**
     * The table <code>Priorities</code>.
     */
    public static final Priorities PRIORITIES = gov.nist.csrc.jooq.tables.Priorities.PRIORITIES;

    /**
     * The table <code>Relateds</code>.
     */
    public static final Relateds RELATEDS = gov.nist.csrc.jooq.tables.Relateds.RELATEDS;

    /**
     * The table <code>Specs</code>.
     */
    public static final Specs SPECS = gov.nist.csrc.jooq.tables.Specs.SPECS;

    /**
     * The table <code>TICMappings</code>.
     */
    public static final Ticmappings TICMAPPINGS = gov.nist.csrc.jooq.tables.Ticmappings.TICMAPPINGS;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public static final SqliteSequence SQLITE_SEQUENCE = gov.nist.csrc.jooq.tables.SqliteSequence.SQLITE_SEQUENCE;
}
